### ISSUE TITLE
Save atlas wont work 

### ISSUE THREAD

**Issue by OVERMEGAKILL** [Grim-es/material-combiner-addon#106]
Hello, Thanks for the Addon,

"Save atlas to..." casting error metallic roughness is missing

![material combiner atlas](https://github.com/user-attachments/assets/8f595bbc-cd79-4f3c-a126-179d65d636f5)

What can I do about it pls?

**Comment by Grim-es** [comment]
Resolved through private messages by switching shader to one of the [supported shaders](https://github.com/Grim-es/material-combiner-addon/issues/98#issuecomment-2003613469).
