### ISSUE TITLE
Unable to combine materials at all.

### ISSUE THREAD

**Issue by HEofOttoman** [Grim-es/material-combiner-addon#116]
Hello, when I try to combine materials, it instead shows me the following error.
![Screenshot 2024-10-20 221000](https://github.com/user-attachments/assets/aca6a3f4-3618-4c77-a142-eade0d18bcff)
I have updated the addon to the latest version from within Blender (as of 20 October 2024 21:58 AEDT), and I am lost on what to do.

**Comment by Grim-es** [comment]
Hello, make sure all materials have enabled [`Use Nodes`](https://blender.stackexchange.com/a/141749) feature.

**Comment by HEofOttoman** [comment]
> Hello, make sure all materials have enabled [`Use Nodes`](https://blender.stackexchange.com/a/141749) feature.

Is there a way to do this quickly? Because I have 10s of materials from a pack.

**Comment by HEofOttoman** [comment]
It also has something about `get_image`

What does that mean?

**Comment by Grim-es** [comment]
> > Hello, make sure all materials have enabled [`Use Nodes`](https://blender.stackexchange.com/a/141749) feature.
> 
> Is there a way to do this quickly? Because I have 10s of materials from a pack.

Open blender's console Window (not the console that is opened after blender launch), and type that command:
```Python
for mat in bpy.data.materials:
    mat.use_nodes = True
```
![image](https://github.com/user-attachments/assets/01d5e5ab-9968-46cb-b84b-b893740fde60)

**Comment by HEofOttoman** [comment]
That worked to fix my problem with making an atlas, but I run into another problem 
![image](https://github.com/user-attachments/assets/aac3a5d3-1856-4ebb-885b-70c9ef7d676c)
I lose a lot of my materials (the white)

**Comment by HEofOttoman** [comment]
I found that the white materials for whatever reason use Principled BDSF, while the materials that retain their color use Diffuse BDSF.
Which one should I use?

**Comment by HEofOttoman** [comment]
I finally fixed the problem, thank you very much for you help. 
![image](https://github.com/user-attachments/assets/b32ce1e7-e36d-4dc2-91fc-0bd8386fd107)
