### ISSUE TITLE
Traceback error?

### ISSUE THREAD

**Issue by sebastianN01** [Grim-es/material-combiner-addon#17]
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'material-combiner-addon-2'

why? i downloaded and installed most recent version as of 18/05/2020

**Comment by DavidLSmyth** [comment]
This tends to happen with versioned blender add-ons. If you unzip, rezip with the name material-combine-addon it should take care of the issue. See https://github.com/Rokoko/rokoko-studio-live-blender/issues/60 for the same problem
