### ISSUE TITLE
I have no idea why this is happening

### ISSUE THREAD

**Issue by Ninkyo** [Grim-es/material-combiner-addon#21]
![image](https://user-images.githubusercontent.com/63518788/100544268-677bc500-324c-11eb-9a63-8eafdb9aadac.png)

It creates a duplicate just to account for this set of polygons yet in the original nothing looks weird.

![image](https://user-images.githubusercontent.com/63518788/100544331-c6d9d500-324c-11eb-9ebb-885697520e2e.png)

![image](https://user-images.githubusercontent.com/63518788/100544356-fc7ebe00-324c-11eb-80e2-eef1eef9bdd0.png)

**Comment by Grim-es** [comment]
Hello, if you have UVs outside of bounds the texture will repeat automatically, but the atlas requires clamped UVs so the texture repeats on atlas. Find that face on UV after atlasing, and move/rescale before atlasing, to fix.

**Comment by Ninkyo** [comment]
> Hello, if you have UVs outside of bounds the texture will repeat automatically, but the atlas requires clamped UVs so the texture repeats on atlas. Find that face on UV after atlasing, and move/rescale before atlasing, to fix.

Thanks, they weren't out of bounds before it seems to happen after atlasing should I move them before atlasing again?
