### ISSUE TITLE
Not working, crashing blender and traceback errors

### ISSUE THREAD

**Issue by vovan-ivanoff** [Grim-es/material-combiner-addon#24]
I have ran into issue. I have 9 material 3 of them with alpha textures and this scheme 
![image](https://user-images.githubusercontent.com/63170128/112539834-86d1cb80-8dc2-11eb-96a4-c0b11c7c6e44.png)
other 6 are just colors with different shader values(like smoothness, metalic, etc) 
and after installing this plugin i`ve clicked generate material list then Save atlas to... button,
![image](https://user-images.githubusercontent.com/63170128/112539906-9d782280-8dc2-11eb-8f5b-1a56b0a5d9e3.png)
 but materials disappeared no atlas created no save file dialogue is shown.
![image](https://user-images.githubusercontent.com/63170128/112538790-4a51a000-8dc1-11eb-8aca-71e2c408ca40.png)
 I have tried reinstalling plugins, reinstalling blender, running as admin, but nothing happens. if click checkbox here 
![image](https://user-images.githubusercontent.com/63170128/112539321-e8de0100-8dc1-11eb-8776-7d628a33812b.png)
blender gives traceback error 
![image](https://user-images.githubusercontent.com/63170128/112538557-09598b80-8dc1-11eb-9129-a3c9cfdd41ea.png)
or just crashes without any error.

What could be problem?
Thanx:)

**Comment by Oriphen** [comment]
I'm also having the same issue.

**Comment by Twilightlicious** [comment]
Same issue here

**Comment by miyanorisako** [comment]
Same issue too.
