### ISSUE TITLE
Cannot install on 2.93

### ISSUE THREAD

**Issue by AlexS2412** [Grim-es/material-combiner-addon#27]
![image](https://user-images.githubusercontent.com/14182708/119732034-b09c8280-be45-11eb-8846-c7e233a5b6ed.png)

**Comment by vvspers** [comment]
Instead of going to releases on the side on the main page click code up top and download the zip from there and it will work in blender 2.93 or Blender 3.0

**Comment by vvspers** [comment]
Instead of going to releases on the side on the main page click code up top and download the zip from there and it will work in blender 2.93 or Blender 3.0

**Comment by Tyler-96** [comment]
@AlexS2412 did you ever resolve this issue?  i have been having it as well.

**Comment by YeloPartyHat** [comment]
Also having this issue even as of 2nd December 2021

**Comment by YeloPartyHat** [comment]
Hi guys, I was able to fix the same looking issue by


- [ ] 1. Start off by removing the plugin, downloading it again, and renaming it to `material-combiner-addon-master.zip` (don't reinstall it just yet)
- [ ] 2. Close Blender then open it up again (this is to clear your console)
- [ ] 3. Open the Blender console by going **Window > Toggle System Console**
- [ ] 4. Try and install the plugin and activate it.
- [ ] 5. You should get something similar to this stating that your plugin can't find some file in `C:\Users:\Your_Name\AppData\Roaming\Blender ...` 
![image](https://user-images.githubusercontent.com/34695601/144386681-826f1541-3a0f-42a5-a65a-685a822850bc.png)

- [ ] 6. Open up the Windows File Explorer and navigate to the Blender 2.93 Scripts > Addons folder. You can find it in the console error message like below. Mine was `C:\Users\Yelo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons`
![image](https://user-images.githubusercontent.com/34695601/144387296-a7216223-86a9-4899-951f-7ad77868a34d.png)

- [ ] 7. Rename the folder called `material-combiner-addon-2.1.1.8`  to  `material-combiner-addon-master`
- [ ] 8. Restart Blender and try activate the plugin again. It should work now.
