### ISSUE TITLE
'ImageFile' not defined when trying to install and activate latest release 

### ISSUE THREAD

**Issue by ROBYER1** [Grim-es/material-combiner-addon#33]
I get this when installing 2.1.1.9 in Blender 3.0 (clean install)
![image](https://user-images.githubusercontent.com/10745594/145718091-9da45899-8f65-4187-aa9d-c91cb1bcec78.png)

I then follow this guide here to work around:
https://github.com/Grim-es/material-combiner-addon/issues/27#issuecomment-984412166

I then get this error:
![image](https://user-images.githubusercontent.com/10745594/145718028-2a984d4b-8d82-4f81-9dcd-ab786c882fb4.png)

**Comment by Daniel-kat** [comment]
same bro :c

**Comment by ROBYER1** [comment]
I rolled back to 2.93 Blender, not using the Windows Store LTS version because that had a access denied error when trying to install Pillow. The actual MSI installer version of 2.93 from the Blender website worked with it just fine.

**Comment by Daniel-kat** [comment]
![imagen](https://user-images.githubusercontent.com/55117813/145737010-937e2099-d33f-4993-bbea-696e3ef7a475.png)
for me still doesn't work

**Comment by Daniel-kat** [comment]
thank you! it worked. but i needed to redownload the plugin
