### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by Dragon092** [Grim-es/material-combiner-addon#34]
Hey,
I am getting a lot of update notifications for version 2.1.2.0 but the version always stays at 2.1.1.9.
I think the __init__.py file still has the version listed as 2.1.1.9, so the updater gets confused?

**Comment by Grim-es** [comment]
Hi, if you are using Blender 3.0+ then version 2.1.1.9 has problems with updating (and some others), need to manually install 2.1.2.0.

**Comment by Dragon092** [comment]
I tried that, but after the installation the version is still listed as 2.1.1.9 in Blender and it tries to update.
![image](https://user-images.githubusercontent.com/1305079/146683532-8914ba4e-b6f5-4b20-bca2-ec9aeff4677d.png)

The init.py in this repository also still has the version listed as 2.1.1.9, could this be the issue?
https://github.com/Grim-es/material-combiner-addon/blob/4acb82f67a5755c29b455e6af9c9afae3ec5b30e/__init__.py#L27
