### ISSUE TITLE
after creating atlas file it destroy the texture and material 

### ISSUE THREAD

**Issue by xalteropsx** [Grim-es/material-combiner-addon#44]
i have an saved output of texture map using on pbr  not inside on blend plz help

**Comment by Grim-es** [comment]
Hello, not all shaders are supported and only one texture per material, which will be in the atlas. For more information https://github.com/Grim-es/material-combiner-addon/issues/29#issuecomment-1020722301

**Comment by xalteropsx** [comment]
is the popular extreme pbr not supported ?

**Comment by xalteropsx** [comment]
![Screenshot_265](https://user-images.githubusercontent.com/103671642/176104310-21ac66d4-23c9-48ff-9031-ed078b2e6d3c.png)

![Screenshot_267](https://user-images.githubusercontent.com/103671642/176104321-147263ee-ff13-4925-b9ca-c995baa497d0.png)

**Comment by Grim-es** [comment]
> is the popular extreme pbr not supported ? @Grim-es

No, it's not, switch to Principled BSDF with only one Image Texture node, or to Diffuse BSDF
