### ISSUE TITLE
Generates wrong atlas and destroys original textures 

### ISSUE THREAD

**Issue by guoodddd** [Grim-es/material-combiner-addon#47]
Hi, after I have graded the material, I click the save atlas button. Then the correct atlas was not generated, and the generated png file only had black and white images, and then the original texture of the model was lost and turned into a white model.
like this.
https://github.com/guoodddd/question/blob/main/no.png
https://github.com/guoodddd/question/blob/main/mater.png
This is the generated atlas
https://github.com/guoodddd/question/blob/main/Atlas_45991.png

**Comment by Grim-es** [comment]
Hello, that might refer to this issue https://github.com/Grim-es/material-combiner-addon/issues/29#issuecomment-1020722301

**Comment by guoodddd** [comment]
> Hello, that might refer to this issue [#29 (comment)](https://github.com/Grim-es/material-combiner-addon/issues/29#issuecomment-1020722301)

I solved this a few weeks ago, but forgot to mention it on github. The main reason is that the material fusion plugin cannot find the corresponding map texture. The solution is to use cat to bake the baked texture and relink it to the model, so that the correct atlas can be generated.
