### ISSUE TITLE
2.1.2.3 Release init.py has wrong version number (says 2.1.2.2)

### ISSUE THREAD

**Issue by ROBYER1** [Grim-es/material-combiner-addon#48]
As in the title, this causes the auto updater to bug out unless you edit it manually in the newest release - https://github.com/Grim-es/material-combiner-addon/releases

**Comment by Grim-es** [comment]
Thanks, fixed on [2.1.2.4](https://github.com/Grim-es/material-combiner-addon/releases/tag/2.1.2.4).
