### ISSUE TITLE
Consistent prompt to download "Pillow"

### ISSUE THREAD

**Issue by BlooDerg** [Grim-es/material-combiner-addon#49]
I cant use this add-on because its constantly prompting me to download pillow even after opening blender as administrator.

**Comment by Grim-es** [comment]
> I cant use this add-on because its constantly prompting me to download pillow even after opening blender as administrator.

Hello, please read [Readme](https://github.com/Grim-es/material-combiner-addon#pillow-installation-process-is-repeated)
