### ISSUE TITLE
Combines textures with different transparency; Duplicates Textures needlessly

### ISSUE THREAD

**Issue by Jwguy** [Grim-es/material-combiner-addon#5]
I've been noticing that the plugin tends to smash all textures down into one like texture based on shared .png files, rather than actual likeness or other settings on the material. This causes textures for things such as expressions for humanoid models (which are often transparent image overlays at varying transparencies and settings) to be flattened into a solid filled texture. This hurts way more than it helps.

Further, I've noticed on a handful of models, one in recent history, that it seems to take a material and duplicate it for seemingly no reason. There's a single material using the texture, from what I can see, but it makes two sections in the combined atlas for it.

**Comment by Grim-es** [comment]
When UV is out of bounds, combiner duplicates the texture to fill the UV, even if it is a bit out.
About transparent images, do you mean to add the ability to generate two materials for transparent and opaque texture atlases?
