### ISSUE TITLE
Can't create atlas

### ISSUE THREAD

**Issue by roadbby** [Grim-es/material-combiner-addon#50]
When I press "save atlas to.." it doesn't direct me to save it anywhere and doesn't combine the materials. It says at the bottom "Duplicates were combined" for some reason.

**Comment by Grim-es** [comment]
> When I press "save atlas to.." it doesn't direct me to save it anywhere and doesn't combine the materials. It says at the bottom "Duplicates were combined" for some reason.

Hello, please read [Readme](https://github.com/Grim-es/material-combiner-addon#after-clicking-save-atlas-to-the-materials-are-simply-merged-or-the-atlas-image-does-not-have-all-the-textures)

**Comment by KazyEXE** [comment]
I had the same issue, packed textures didn't help it. It was working fine in Blender 2.9 but 3.2 had the issue for me. #54 fixed it on my end.
