### ISSUE TITLE
Atlas won't generate, materials don't actually combine, textures get reassigned, all materials are Principled BDSF

### ISSUE THREAD

**Issue by TacticalNerd1963** [Grim-es/material-combiner-addon#52]
So my model has 6 materials. As I'm trying to create an atlas for these materials, I keep seeing no atlas generated, I STILL have 6 materials, and the textures are looking... odd. The python traceback error I'm getting is as follows-

Python: Traceback (most recent call last):
  File "C:\Users\patri\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\material-combiner-addon-master\operators\combiner\combiner.py", line 33, in execute
    assign_comb_mats(scn, self.data, self.mats_uv, atlas)
  File "C:\Users\patri\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 277, in assign_comb_mats
    comb_mats = get_comb_mats(scn, atlas, mats_uv)
  File "C:\Users\patri\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 241, in get_comb_mats
    existed_ids = [int(i.mat.name.split('_')[-2]) for i in scn.smc_ob_data if (i.type == 1) and
  File "C:\Users\patri\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 241, in <listcomp>
    existed_ids = [int(i.mat.name.split('_')[-2]) for i in scn.smc_ob_data if (i.type == 1) and
ValueError: invalid literal for int() with base 10: 'atlas'

Before and after screenshots are posted. A little help here?
![unknown1](https://user-images.githubusercontent.com/112349483/187093966-5d24c8ad-ede5-40e9-92ee-3293c3ccecb5.png)
![unknown](https://user-images.githubusercontent.com/112349483/187093968-bbe90c95-45cd-436b-87ea-d518e636c42c.png)

**Comment by Grim-es** [comment]
Hello, looks like you are not have your textures unpacked, more info [here](https://github.com/Grim-es/material-combiner-addon#after-clicking-save-atlas-to-the-materials-are-simply-merged-or-the-atlas-image-does-not-have-all-the-textures).
You could also try the dev build that is not require pillow library and uses another method of finding the right texture [Download](https://github.com/Grim-es/material-combiner-addon/archive/refs/heads/dev-build.zip).

**Comment by TacticalNerd1963** [comment]
> Hello, looks like you are not have your textures unpacked, more info [here](https://github.com/Grim-es/material-combiner-addon#after-clicking-save-atlas-to-the-materials-are-simply-merged-or-the-atlas-image-does-not-have-all-the-textures). You could also try the dev build that is not require pillow library and uses another method of finding the right texture [Download](https://github.com/Grim-es/material-combiner-addon/archive/refs/heads/dev-build.zip).

When I go to File>External Data>Unpack resources it says "No packed files to unpack," so the textures are definitely fine. I also tried the dev build to combine the textures but I'm getting the exact same results

**Comment by Mysteryem** [comment]
Rename your materials so that they don't start with `material_atlas_`, that should fix the Python error.
