### ISSUE TITLE
[Question] Possible to Deselect ALL?

### ISSUE THREAD

**Issue by KazyEXE** [Grim-es/material-combiner-addon#55]
Hello!

I have a scene with a very large amount of smaller objects (5,000+), plus one large object with lots of materials.

Is it possible to deselect EVERYTHING? When using Material Combiner, it defaults to selecting every material. I want to only select the materials on the large object. Going through every other object one by one deselecting them isn't feasible.

**Comment by Grim-es** [comment]
Hello, it's not possible to deselect all through the UI. But you can do it with a custom script. Open a Text Editor window, write this code and click the Run Script button:
```Python
import bpy

for i in bpy.context.scene.smc_ob_data:
    i.used = False
```
![image](https://user-images.githubusercontent.com/20622400/194100012-a3e55c61-80dc-4035-a594-8f47fca2e166.png)
