### ISSUE TITLE
Blender 2.8 Support

### ISSUE THREAD

**Issue by ProbablePrime** [Grim-es/material-combiner-addon#6]
With Blender 2.8, just around the corner are there plans to support Blender 2.8 within this addon?

**Comment by kkartaltepe** [comment]
I see the author has +1'ed this comment but not responded. Is there any working going on to support blender 2.8 currently and/or would PRs be accepted if they do implement such support, or is this repo abandoned and anyone willing to do this should fork the project?

**Comment by Grim-es** [comment]
I plan to rewrite some code and UI, make it more comfortable to work with, and then do supporting for 2.8, but currently i have no time for that so I'll continue to work on summer

**Comment by ProbablePrime** [comment]
I'm taking a stab at this over at: 
https://github.com/ProbablePrime/material-combiner-addon/commits/master

Right now getting it to work on 2.8 is the priority after that i'll tidy up all the mess i've made and ensure its backwards compatible.

So far so good though, Look the UI partially loads
![image](https://user-images.githubusercontent.com/8791132/61586041-7c582c80-ab1f-11e9-9a0e-421182af7dd6.png)

**Comment by Grim-es** [comment]
> I'm taking a stab at this over at:
> https://github.com/ProbablePrime/material-combiner-addon/commits/master
> 
> Right now getting it to work on 2.8 is the priority after that i'll tidy up all the mess i've made and ensure its backwards compatible.
> 
> So far so good though, Look the UI partially loads
> ![image](https://user-images.githubusercontent.com/8791132/61586041-7c582c80-ab1f-11e9-9a0e-421182af7dd6.png)

Thanks for your efforts, support for blender 2.80 released.

**Comment by ProbablePrime** [comment]
Oh, wow, thank you!
