### ISSUE TITLE
Using an old atlas files?

### ISSUE THREAD

**Issue by Refundmybirth** [Grim-es/material-combiner-addon#61]
![Screenshot 2023-05-01 181431](https://user-images.githubusercontent.com/132309482/235542889-db4471be-7526-4826-9332-0094655ba0dd.png)
![Screenshot 2023-05-01 181415](https://user-images.githubusercontent.com/132309482/235542892-43952862-4051-43e1-ac01-d9376862bcaf.png)

I did exract files, I dont know what happening.

**Comment by Grim-es** [comment]
Looks like VRoid uses custom shader attributes and "special" nodes to achieve the desired effect, which cannot be directly applied to the texture without baking. To achieve a similar result, consider keeping the atlas as it is and using software like Photoshop, Gimp, or Paint.NET to perform image mixing and apply color corrections.
