### ISSUE TITLE
Latest update makes some textures black

### ISSUE THREAD

**Issue by chocolateimage** [Grim-es/material-combiner-addon#70]
After the latest update when trying to combine the materials some textures will go black and then only part of the final texture is done and some parts of the final texture is black.

**Comment by Grim-es** [comment]
Hello, please provide some sample screenshots. What "shader" is your materials using, are your textures generated in blender, or are the files on disk/packed into a blend? If you click on the gear icon next to a material in the material list, will it show black color instead of white?

**Comment by chocolateimage** [comment]
Because of this bug I uninstalled and installed the old version again, but because I wanted to show you the bug again, I installed the new version again but it worked again, seemed like a bug in the updater.
