### ISSUE TITLE
Wont merge more than two materials

### ISSUE THREAD

**Issue by Verdammt-hans** [Grim-es/material-combiner-addon#79]
it wont merge more than two materials, and im not doing Anything wrong, its the Latest Version, and Just the Default BSDF shader thats only being used, nothing else. With an Image texture, thats all. using images that are Not Packed into the Blender File, just images out of my Folders, when i use two materials, it works. but anymore and it breaks, making either the textures black or missing some of them.

**Comment by Grim-es** [comment]
Hello, please check that image texture node has `Image Texture` name, without any additional .001 at the end or something else. To check that - select image texture node on Shading tab, and press `N` key on the keyboard to open right side panel, it will have a `name` and `label` properties, you need to check `name`.
