### ISSUE TITLE
Root directory save issue

### ISSUE THREAD

**Issue by OneVoltTen** [Grim-es/material-combiner-addon#8]
![2019-08-18 03_52_59-Window](https://user-images.githubusercontent.com/11697505/63215616-ac214100-c16c-11e9-8004-57efbb6bcda0.png)
Replicate by separate [...], join, atlas combine materials several times until it breaks - trying to save in the root directory causing an error.

**Comment by OneVoltTen** [comment]
Tested in Windows and Linux, seems to occur more likely when separate by Loose parts/Shapes.

**Comment by Grim-es** [comment]
This error means that you do not have permission to overwrite existing file or access to this directory (run Blender with Administrative privileges)
