### ISSUE TITLE
UV Mapping not Perfect

### ISSUE THREAD

**Issue by heare2code** [Grim-es/material-combiner-addon#81]
Whenever I use this plugin, everything seems to shift ever so slightly. This becomes a problem when models have their UV maps set up so perfectly that these shifts could throw everything off.
Examples:
![image](https://github.com/Grim-es/material-combiner-addon/assets/102204285/83d33ec3-7414-47dd-8bb0-08b529b0ca38)
![image](https://github.com/Grim-es/material-combiner-addon/assets/102204285/64585c4e-a222-4fc3-99cc-89645ee61091)
![image](https://github.com/Grim-es/material-combiner-addon/assets/102204285/6eb48829-902b-4da7-9092-03a8e723212b)
![image](https://github.com/Grim-es/material-combiner-addon/assets/102204285/54807b25-307f-4bee-a01e-bce7c27b396c)
![image](https://github.com/Grim-es/material-combiner-addon/assets/102204285/6752d114-05db-43b2-9b2e-e79be0d06c91)
![image](https://github.com/Grim-es/material-combiner-addon/assets/102204285/42e5dcf1-e60d-4a91-a59b-6abac1901853)
Not sure if this is a problem with my model (considering ripped Nintendo models tend to fuck people over) or if it's this plugin doing something.
I tried changing all the properties and none of them fix or reduce this effect. I can supply the model if needed.

**Comment by Grim-es** [comment]
This issue can occur when textures are too small. The UVs scale down by 1 pixel, ensuring that neighboring textures do not encroach on them. To avoid this, you can manually remove the `+ 2` from the **`margin`** and the `1 +` from the **`border_margin`** in this file: https://github.com/Grim-es/material-combiner-addon/blob/55a235dcd93455994aec1226bbbfd78092ff6463/operators/combiner/combiner_ops.py#L339

**Comment by heare2code** [comment]
>To avoid this, you can manually remove the `+ 2` from the **`margin`** and the `1 +` from the **`border_margin`** in this file:
> 
> https://github.com/Grim-es/material-combiner-addon/blob/55a235dcd93455994aec1226bbbfd78092ff6463/operators/combiner/combiner_ops.py#L339

I tried this and it worked, thanks! Maybe you should put this somewhere in case someone else has this issue, like in the read me or as a setting in the plugin.
