### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by rico345100** [Grim-es/material-combiner-addon#90]
zero explanation how to use this. only install steps exists. what the heck should i use this stuff?

**Comment by Grim-es** [comment]
Simply deselect the materials you don't want to combine into the atlas on the MatCombiner panel located on the right side of the 3D-view window if it's even needed. Afterward, click "Save atlas too...". That's all. You can also find several YouTube tutorials demonstrating the use of this addon for reference.

**Comment by EhoNo1** [comment]
I second rico's request, this project really needs a brief tutorial on how to use for people who are new to blender and/or new to using addons. Without a getting started section it assumes that users already know how to use it. I had to fallback on my intuitions on how other plugins worked to know where to start using this one.

A small section in the readme with a description of where the tool's menu is and/or a screenshot of where it is would go a long way.

I'd be happy to contribute to that if you're okay with it, @Grim-es.

**Comment by Rycia** [comment]
This should be on the front page.
